apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-app
spec: 
    replicas: 1
    selector:
      matchLabels:
        app: stock-app
    template:
      metadata:
        labels:
          app: flask-app
      spec:
        containers:
          - name: flask-app
            image: dhruvrs/flask-app:latest
            ports:
              - containerPort: 5000